base/urls.py
from django.urls import path, include
from . import views

app_name = 'base'
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
]

listings/urls.py
from django.urls import path, include

import listings.views as views

app_name = 'listings'

urlpatterns = [
    path("", views.HX_List.as_view(), name="HX_List"),
    path("create/", views.ListingCreate.as_view(), name="create"),
    path("randomize/", views.ListingRandomizer.as_view(), name="randomize"),
    path("detail/<int:pk>", views.ListingDetail.as_view(), name="detail"),
    path("update/<int:pk>", views.ListingUpdate.as_view(), name="update"),
    path("delete/<int:pk>", views.ListingDelete.as_view(), name="delete"),
]

mocktions/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler400, handler500, handler403
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace='base')),
    path('', include("django_backblaze_b2.urls", namespace="b2")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('images/', include("images.urls", namespace="images")),
    path('listings/', include('listings.urls', namespace='listings')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'base.views.handler404'
handler500 = 'base.views.handler500'
handler403 = 'base.views.handler403'

listings/html/templates/add_images.html
{% extends 'base/html/templates/base.html' %}
{% load static %}
{% block body %}
    {% include "images/html/includes/main.html" with imageset=listing.imageset %}

    <button class="btn btn-primary my-3" 
            hx-post="{% url 'listings:add_images' listing.id %}">
        Next: Review</button>
{% endblock %}

listings/html/templates/create.html
{% extends 'base/html/templates/base.html' %}
{% load static %}
{% block body %}

    {# Randomize #}
    <div class="alert alert-info" role="alert">
        <h4 class="alert-heading">Test it out!</h4>
        <p>Because this isn't a "real" site, feel free to click the button below to automatically generate a random listing, including images.</p>
        <a href="{% url 'listings:randomize' %}" class="btn btn-primary">Generate a random listing</a>
        <p class="small">Note: this can take some time to generate the images.</p>
    </div>
    <hr class="my-3" />
    {% comment %}
        Make sure the view provides the appropriate action to this template 
        to distinguish between create and update.
    {% endcomment %}
    <form id="id_listing_create_form" action="{{ submit_url }}" method="POST">
        {% csrf_token %}
        {% for field in form %}
            <div class="mb-3">
                <div class="form-label">{{ field.label }}</div>
                <div>{{ field }}</div>
                <div class="form-help">{{ field.errors }}</div>
            </div>
        {% endfor %}
    </form>
    
    {% comment %}
        When first rendered, an imageset object is created in the view and the form's 
        initial value for that field is populated. Therefore we can load the image 
        uploader here using that imageset's ID by accessing the relevant form field's 
        value.
    {% endcomment %}
    {% with form.imageset.value as imageset_id %}
        {% include "images/html/includes/main.html" with imageset_id=imageset_id %}
    {% endwith %}

    <button class="btn btn-primary my-3" form="id_listing_create_form" type="submit">Submit</button>
{% endblock %}

listings/html/templates/delete.html
{% extends 'base/html/templates/base.html' %}
{% load static %}
{% block body %}
    <form method="POST">
        {% csrf_token %}
        <p>Confirm deletion of listing, "{{ listing.title }}".</p>
        <button type="submit" class="btn btn-danger">Yes, delete this listing</button>
    </form>
{% endblock body %}

listings/html/templates/detail.html
{% extends 'base/html/templates/base.html' %}
{% load static %}
{% block body %}
    {% include "listings/html/includes/listing_large.html" with listing=listing %}
{% endblock %}

listings/html/templates/list_large.html
<div id="id_listings_list" hx-swap="outerHTML">
    <div class="container g-3">
        {# TODO: switch display mode: large, small, list #}
        <div class="row">
            {% for listing in page_obj %}
                <div class="col-md-6 mb-3">
                    {% include 'listings/html/includes/listing_large.html' with listing=listing %}
                </div>
            {% endfor %}
        </div>
    </div>
</div>

{% include "base/html/includes/pagination_buttons.html" with page_obj=page_obj %}

listings/html/templates/list_list.html
<div id="id_listings_list" hx-swap="outerHTML">
    <div class="container g-3">
        {# TODO: switch display mode: large, small, list #}
        {% for listing in page_obj %}
            <div class="row">
                <div class="col-12 mb-3">
                    {% include 'listings/html/includes/listing_list.html' with listing=listing %}
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% include "base/html/includes/pagination_buttons.html" with page_obj=page_obj %}

listings/html/templates/list_small.html
<div id="id_listings_list" hx-swap="outerHTML">
    <div class="container g-3">
        {# TODO: switch display mode: large, small, list #}
        <div class="row">
            {% for listing in page_obj %}
                <div class="col-md-3 mb-3">
                    {% include 'listings/html/includes/listing_small.html' with listing=listing %}
                </div>
            {% endfor %}
        </div>
    </div>
</div>

{% include "base/html/includes/pagination_buttons.html" with page_obj=page_obj %}