accounts/urls.py
from django.urls import path
import accounts.views as views
from django.urls import reverse, reverse_lazy

app_name = 'accounts'
urlpatterns = [
    path('', views.index, name="index"),
    path('delete/<int:pk>', views.DeleteAccount.as_view(), name='delete_account'),
    path('login/',  views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('profile/<int:pk>', views.Profile.as_view(), name='profile'),
    path('register/', views.Register.as_view(), name='register'),
]

base/urls.py
from django.urls import path, include
from . import views

app_name = 'base'
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
]

mocktions/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler400, handler500, handler403
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace='base')),
    path('', include("django_backblaze_b2.urls", namespace="b2")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    path('images/', include("images.urls", namespace="images")),
    path('listings/', include('listings.urls', namespace='listings')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'base.views.handler404'
handler500 = 'base.views.handler500'
handler403 = 'base.views.handler403'

accounts/html/templates/delete_account.html
{% extends 'base/html/templates/base.html' %}
{% load static %}
{% load breadcrumbs %}

{% block breadcrumb %}
    {% breadcrumb_url 'Home' 'base:index' %}
    {% breadcrumb 'Delete profile' %}
{% endblock breadcrumb %}

{% block body %}

    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col">
            <div class="card mx-auto">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="mb-3 form-check">
                                {{ field }}
                                <label class="form-check-label" for="{{ field.auto_id }}">{{ field.label }}</label>
                            </div>
                        {% endfor %}
                        <input type="submit" class="btn btn-danger d-block" value="Confirm">
                    </form>
                </div>
            </div>
        </div>
        <div class="col-sm-3"></div>
    </div>
      
{% endblock body %}

accounts/html/templates/login.html
{% extends 'base/html/templates/base.html' %}
{% load static %}
{% block body %}
    <h1>Login</h1>
    <form action="{% url 'accounts:login' %}" method="post" class="container my-5 p-0">
        {% csrf_token %}{% for field in form %}
            <div class="row mb-3">
                <div class="col-sm-4">
                    <div class="form-floating">
                        {{ field }}
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        <div class="text-danger text-small">
                            <ul class="ml-0">
                                {% for error in field.errors  %}
                                    <li class="text-danger small">{{ error }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-sm-8"></div>
            </div>
        {% endfor %}
        <div class="text-danger text-small">
            <ul class="ml-0">
                {% for error in form.non_field_errors %}
                    <li class="text-danger small">{{ error }}</li>
                {% endfor %}
            </ul>
        </div>

        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    <p>Don't have an account? <a href="{% url 'accounts:register' %}">Register here.</a></p>
{% endblock body %}

accounts/html/templates/logout.html
{% extends 'base/html/templates/base.html' %}
{% load static %}
{% load breadcrumbs %}

{% block breadcrumb %}
    {% breadcrumb_url 'Home' 'base:index' %}
    {% breadcrumb 'Logout' %}
{% endblock breadcrumb %}

{% block body %}

    <form action="{% url 'accounts:logout' %}" method="POST" class="my-5">
        {% csrf_token %}
        <input type="submit" class="btn btn-outline-dark" value="Click here to log out of your account.">
    </form>
      
{% endblock body %}

accounts/html/templates/profile.html
{% extends 'base/html/templates/base.html' %}
{% load static %}
{% load breadcrumbs %}

{% block breadcrumb %}
    {% breadcrumb_url 'Home' 'base:index' %}
    {% breadcrumb_url 'Profiles' %}
    {% breadcrumb_url request.user.username %}
{% endblock breadcrumb %}

{% block body %}
    
    {% include "listings/html/includes/main.html" with list_by="user" %}

    <h2>Delete your account</h2>
    <a href="{% url 'accounts:delete_account' pk=request.user.id %}">Click here to delete your account.</a>
{% endblock body %}

accounts/html/templates/register.html
{% extends "base/html/templates/base.html" %}

{% block body %}

    {% include 'accounts/html/includes/profile_form.html' with form=form form_action='register' %}

    <p>Already have an account? <a href="{% url 'accounts:login' %}">Log In here.</a></p>

{% endblock %}